name: Rebuild and deploy book to gh-pages branch
on:
  push:
    branches:
      - main
    paths:
      - source/**
      
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    container: ubcdsci/py-intro-to-ds:temporary
    permissions:
      contents: write
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: 'main'

      - name: Build the book
        run: |
          jupyter-book build source

       # Push the book's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: source/_build/html
          force_orphan: true

