name: "Rebuild and deploy PR version of book to gh-pages branch in pull###/ folder"
on:
  pull_request:
    types: [reopened, opened, synchronize]
    paths:
      - source/**
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          ref: ${{ github.head_ref }}
          
      - name: Build the book
        run: |
          ./build_html.sh

       # Push the book's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: source/_build/html
          keep_files: true
          destination_dir: pull${{ github.event.number }}
          # force_orphan: true # once peaceiris updates to v4, change this to true and keep_files: true for the PR / main branch deploy previews



