name: Rebuild and publish new ubcdsci/py-intro-to-ds image on DockerHub
on:
  push:
    branches:
      - dev
    paths:
      - Dockerfile
jobs:
  rebuild-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      workflows: write
    steps:
    - name: Checkout dev
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
        ref: 'dev'
    - name: Rebuild and publish image
      id: rebuild
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: ubcdsci/py-intro-to-ds
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
    - name: Update build_html.sh script
      run: |
        sed --debug 's/ubcdsci\/py-intro-to-ds:[[:alnum:]]\+/ubcdsci\/py-intro-to-ds:${{ steps.rebuild.digest }}/g' build_html.sh > build_html.tmp && mv build_html.tmp build_html.sh
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add build_html.sh
        git commit -m "update build_html.sh script with new docker image"
    - name: Update build_book.yml
      run: |
        sed --debug 's/ubcdsci\/py-intro-to-ds:[[:alnum:]]\+/ubcdsci\/py-intro-to-ds:${{ steps.rebuild.digest }}/g' .github/workflows/build_book.yml > build_book.tmp && mv build_book.tmp .github/workflows/build_book.yml
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .github/workflows/build_book.yml
        git commit -m "update build_book.yml script with new docker image"
    - name: Push changes to build scripts
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'dev'
